use usuarios_web;

INSERT INTO `opciones` (`id`, `opcion`, `descripcion`, `validacion`) VALUES
(1, 1, 'Java', 'False'),
(2, 1, 'Python', 'True'),
(3, 1, 'Php', 'False'),
(4, 2, 'No existe diferencia', 'True'),
(5, 2, 'Una variable solo recibe valores definidos por el usuario', 'False'),
(6, 2, 'Un atributo solo recibe valores definidos por el programa', 'False'),
(7, 2, 'Ninguna de las anteriores', 'False'),
(8, 3, 'No es conveniente ya que esto provocaria errores cuando se intente acceder a la tabla que la contenga', 'False'),
(9, 3, 'Si es conveniente ya que esto nos ayuda a relacionar los datos de cada una de las tablas de la db', 'True'),
(10, 3, 'Si es conveniente ya que esto provocaria que no necesitemos usar llaves primarias', 'False'),
(11, 4, 'cd', 'False'),
(12, 4, 'chmod', 'False'),
(13, 4, 'mkdir', 'True'),
(14, 4, 'dir', 'False'),
(15, 4, 'cls', 'False'),
(16, 4, 'ls', 'False'),
(17, 5, 'No es importante ya que la pc igual funcionaria sin problemas', 'False'),
(18, 5, 'Si es importante que se cuente con un sistema operativo ya que la pc no funcionaria', 'True'),
(19, 5, 'Depende del sistema operativo, si hablamos de un sistema operativo Linux este provocaria que la maquina no funcione', 'False'),
(20, 5, 'Ninguna de las anteriores', 'False'),
(21, 6, 'cd...', 'False'),
(22, 6, 'dir --t', 'False'),
(23, 6, 'cd ../../../../../..', 'True'),
(24, 6, 'ls -qq', 'False'),
(25, 7, 'Ninguna de los 2 tipos de busqueda sirven para nada ya que ninguno tienen bajo rendimiento', 'False'),
(26, 7, 'Usar la busqueda secuencial seria lo mejor', 'False'),
(27, 7, 'Usar la busqueda indexada seria lo mejor', 'True'),
(28, 7, 'Usar la busqueda indexada seria una locura ya que esto no sirve para realizar ningun tipo de busqueda', 'False'),
(29, 8, 'example', 'False'),
(30, 8, 'select', 'False'),
(31, 8, 'inner join', 'False'),
(32, 8, 'explain', 'True'),
(33, 9, 'El algoritmo mas rapido es el que tiene 20.000 lineas de codigo', 'False'),
(34, 9, 'El algoritmo mas rapido es el que tiene 150.000 lineas de codigo', 'False'),
(35, 9, 'Todo depende de como se los halla escrito y de la maquina en donde se ejecute', 'True'),
(36, 9, 'Todo depende de el lenguaje de programacion', 'False'),
(37, 10, 'Windows', 'False'),
(38, 10, 'Linux', 'False'),
(39, 10, 'Unix', 'True'),
(40, 10, 'Solaris', 'False'),
(41, 10, 'Mack OX', 'False');

INSERT INTO `preguntas` (`id`, `pregunta`, `opcion`) VALUES
(1, 'Que lenguaje de programacion es mas rapido?', 1),
(2, 'Que diferencia existe entre un atributo y una variable?', 2),
(3, 'Es conveniente usar llaves foraneas en mysql?', 3),
(4, 'Que comando se utiliza en el sistema operativo Linux para crear una carpeta?', 4),
(5, 'Es importante que una pc tenga un sistema operativo?', 5),
(6, 'Seleccione el comando que considere que esta bien escrito.', 6),
(7, 'En terminos de velocidad, es mejor usar busquedas de manera secuencial o busqueda indexada?', 7),
(8, 'Que comando debo usar para analizar las acciones que esta haciendo mi consulta sql?', 8),
(9, 'Si tenemos 2 algoritmos, uno cuenta con 20.000 lineas de codigo y el otro cuenta con 150.000, usted puede saber rapidamente cual es mas rrapido?', 9),
(10, 'Cual es el sistema operativo mas seguro de hoy en dia?', 10);

INSERT INTO `usuarios` (`id`, `usuario`, `password`, `email`, `tipo_usuario`, `token`) VALUES
(1, 'Admin', '1234', 'admin@gmail.com', 'Administrador','fd081b3aee0e3621f41190aa971cb9a5');